sudo: required

language: go

env:
  - REPO=otobrglez/socol

services:
 - docker

before_script:
  - docker login --username=otobrglez --email=otobrglez@gmail.com -p $DOCKER_PASS
  - docker build -t $REPO -f Dockerfile .

script:
  - go test -v ./...
  - docker run -ti -p 127.0.0.1:5000:5000 -d $REPO && sleep 3
  - curl -s --retry 3 --retry-delay 5 -v "http://127.0.0.1:5000/stats?url=http://www.youtube.com/watch?v=t-wFKNy0MZQ"

after_success:
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker push $REPO
